### ISSUE TITLE
When does the package support the NCS2.0?

### ISSUE THREAD

**Issue by MengNan-Li** [intel/ros_intel_movidius_ncs#102]

**Comment by chaoli2** [comment]
@MengNan-Li 
We will support the latest NCSDK as a part of Intel [OpenVINO ](https://software.intel.com/zh-cn/openvino-toolkit)in future. So we do not have a plan to support NCSDKv2 yet.

**Comment by MengNan-Li** [comment]
@chaoli2 
OK, Thinks. Does this‘s mean the intel OpenVINO will include NCSDK and ncappzoo? And, can we use the [ros_object_analytics](https://github.com/intel/ros_object_analytics) function in the OpenVINO?

**Comment by chaoli2** [comment]
@MengNan-Li 
Intel OpenVINO will include new NCSDK. For ncappzoo, we didn't receive certain information that it will be included or not, but I guess it will :)

When the ROS/ROS2 OpenVINO project is done, we'll add its support for [ros_object_analytics](https://github.com/intel/ros_object_analytics) and [ros2_object_analytics](https://github.com/intel/ros2_object_analytics). So you can use their function in OpenVINO in the future. We may first support ROS2 version earlier than ROS.

**Comment by MengNan-Li** [comment]
I got it. Thinks again!
