### ISSUE TITLE
Use of ZED camera

### ISSUE THREAD

**Issue by sebo361** [intel/ros_intel_movidius_ncs#103]
Have you tried to run it with a ZED camera (https://www.stereolabs.com/zed-mini/)? 
Instead of using the "usb_cam" or "realsense_cam" node, I would like to use it with ZED camera.. Is there any existing work related to that?

**Comment by chaoli2** [comment]
@sebo313 
I checked the [ROS community](http://wiki.ros.org/zed-ros-wrapper) and [github](https://github.com/stereolabs/zed-ros-wrapper), and found that ZED camera is already supported. 
So just follow [this guide](https://github.com/intel/ros_intel_movidius_ncs/blob/master/doc/video_classification.md#2-run-with-other-ros-supported-cameras-1) to use it in our project.

**Comment by chaoli2** [comment]
Since we do not have ZED camera in hand, we are not able to verify practical result. So please provide logs if there is any issue when you enable ZED camera.
