### ISSUE TITLE
Crop image before sending into classifier

### ISSUE THREAD

**Issue by sebo361** [intel/ros_intel_movidius_ncs#104]
Hi,
i would like to crop my input image before sending into the detection classifier. The image of the USB camera has dimension of 2560x720 and i would like to half it to 1280x720 before sending it into classifier. So in callback function (https://github.com/intel/ros_intel_movidius_ncs/blob/26b8e2b6a04503befd3f260b8d06886087bd15de/movidius_ncs_stream/src/ncs_nodelet.cpp#L248-L249) tried with following code:

cv::Rect roi;
roi.x = 0;
roi.y = 0;
roi.width = 1280;
roi.height = 720;

cv::Mat cropped = camera_data(roi);

FUNP_D detection_result_callback = boost::bind(&NCSImpl::cbGetDetectionResult, this, _1, _2);
  ncs_manager_handle_->detectStream(cropped, detection_result_callback, image_msg);

But unfortunately it does not work. Any idea to solve this problem?

**Comment by chaoli2** [comment]
@sebo313 
That's somehow strange... Will you please have a try to update the arguments in [camera launch file](https://github.com/intel/ros_intel_movidius_ncs/blob/26b8e2b6a04503befd3f260b8d06886087bd15de/movidius_ncs_launch/launch/ncs_camera.launch#L55)? These arguments will be extracted and used for [result parse](https://github.com/intel/ros_intel_movidius_ncs/blob/26b8e2b6a04503befd3f260b8d06886087bd15de/movidius_ncs_lib/src/ncs.cpp#L163).
