### ISSUE TITLE
catkin_ws/src/ros_intel_movidius/movidius_ncs_lib" does not exist.

### ISSUE THREAD

**Issue by patrickpoirier51** [intel/ros_intel_movidius_ncs#105]
Following these instructions:
cd ~/catkin_ws/src
git clone https://github.com/intel/object_msgs
git clone https://github.com/intel/ros_intel_movidius_ncs.git
cd ros_intel_movidius_ncs
git checkout master
cd ~/catkin_ws

using catkin build
CMake Error: The source directory "/home/patrick/catkin_ws/src/ros_intel_movidius/movidius_ncs_lib" does not exist.
checked the structure of ros_intel_movidius_ncs is a clone

**Comment by chaoli2** [comment]
@patrickpoirier51 
I notice that the package name is wrong in the CMake Error message: 
 "**ros_intel_movidius**/movidius_ncs_lib", which should be "**ros_intel_movidius_ncs**/movidius_ncs_lib".

If above mistake is only typo when you open this issue, will you please show me project structure with this command?
 ```tree ~/catkin_ws/src/ros_intel_movidius_ncs -L 2```

BTW, do you use the original build command "catkin_make" without any paramenter?

**Comment by patrickpoirier51** [comment]
Hello, thanks for your fast answer and pointing me to the right direction
 ;-)
 I simply rebuilded catkin from scratch and it compiled OK
