### ISSUE TITLE
Do you have plan to support detection networks, such as yolo?

### ISSUE THREAD

**Issue by yuanyuanli85** [intel/ros_intel_movidius_ncs#5]
The CNN models listed in README are used for classification.  Do you have plan to add the support for detection network, such as YOLO and SSD?  It would be cool to have those kind of support.

**Comment by xhuan28** [comment]
Thanks for your question. Yes, I am investigating different detection networks, such as tiny yolo, yolov2 on NCS. And the support for detection network will be added in this ROS package at an appropriate time.

**Comment by fiorano10** [comment]
Any update for yolov2?
