### ISSUE TITLE
No category files in ncaapzoo?

### ISSUE THREAD

**Issue by FernandezR** [intel/ros_intel_movidius_ncs#59]
The category files are not present in ncappzoo even after running make in the data directory and this causes the server to crash. Can you add the category files or point me to where they are located?

Thanks

**Comment by chaoli2** [comment]
@FernandezR 
The label files are contained in this project. You can copy them to ncappzoo with below command:
`cp ~/catkin_ws/src/ros_intel_movidius_ncs/data/labels/* /opt/movidius/ncappzoo/data/ilsvrc12/`
