### ISSUE TITLE
load model

### ISSUE THREAD

**Issue by daming5432** [intel/ros_intel_movidius_ncs#62]
How can I load several models simultaneously?

**Comment by daming5432** [comment]
When I load two models, the first is ok bu the second return MVNC_BUSY.

**Comment by daming5432** [comment]
When I load two models, the first is ok but the second return MVNC_BUSY.

**Comment by xhuan28** [comment]
Do you mean you would like to run 2 models on one NCS device? It is not supported currently. But we are developing a feature that supports inference on several NCS devices with different models simultaneously. This feature will be implemented in next release which is going to be ready this month. Stay tuned.

**Comment by xhuan28** [comment]
May I know what the user scenario is? Why you need load two CNN models on one device simultaneously.

**Comment by chaoli2** [comment]
Close this thread since no response. Feel free to re-open this issue when need further assist.
