### ISSUE TITLE
Could not find a package configuration file provided by "object_msgs" 

### ISSUE THREAD

**Issue by manhha1402** [intel/ros_intel_movidius_ncs#63]
I tried to run "catkin_make" command the ros movidius, it showed the error that ros cannot find package "object_msgs" in CMakeLists.txt file. Since I am a beginner with ROS so how can I get this package ?
I am using ros kinetic
Thanks!

**Comment by xhuan28** [comment]
I guess you are using devel branch of the code. Actually, this branch is under development and unstable. Please switch branch to master with tag v0.5.0(https://github.com/intel/ros_intel_movidius_ncs/tree/v0.5.0), your issue should not exist any more.

**Comment by manhha1402** [comment]
Thanks !
