### ISSUE TITLE
Couldn't run movidius node with D435 camera, librealsense2

### ISSUE THREAD

**Issue by manhha1402** [intel/ros_intel_movidius_ncs#64]
Hi,
I tried to follow the instruction(https://github.com/intel/ros_intel_movidius_ncs/blob/master/doc/video_classification.md#googlenet) to stream D435 camera with the command:
# Option 1: RealSense
roslaunch movidius_ncs_launch ncs_camera.launch cnn_type:=alexnet camera:=realsense

and got the error:

Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/__init__.py", line 306, in main
    p.start()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 268, in start
    self._start_infrastructure()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 217, in _start_infrastructure
    self._load_config()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 132, in _load_config
    roslaunch_strs=self.roslaunch_strs, verbose=self.verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/config.py", line 451, in load_config_default
    loader.load(f, config, verbose=verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 748, in load
    self._load_launch(launch, ros_config, is_core=core, filename=filename, argv=argv, verbose=verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 720, in _load_launch
    self._recurse_load(ros_config, launch.childNodes, self.root_context, None, is_core, verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 654, in _recurse_load
    default_machine, is_core, verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 684, in _recurse_load
    val = self._include_tag(tag, context, ros_config, default_machine, is_core, verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 95, in call
    return f(*args, **kwds)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 588, in _include_tag
    inc_filename = self.resolve_args(tag.attributes['file'].value, context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 183, in resolve_args
    return substitution_args.resolve_args(args, context=context.resolve_dict, resolve_anon=self.resolve_anon)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 370, in resolve_args
    resolved = _resolve_args(resolved, context, resolve_anon, commands)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 383, in _resolve_args
    resolved = commands[command](resolved, a, args, context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 151, in _find
    source_path_to_packages=source_path_to_packages)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 197, in _find_executable
    full_path = _get_executable_path(rp.get_path(args[0]), path)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 203, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)

I am able to launch the realsense2 node on my computer. 
![error](https://user-images.githubusercontent.com/20105284/37465897-b5bc3382-285c-11e8-8dcd-299d8e9c4291.png)

Can anyone tell me how to solve it ?
Thanks

**Comment by xhuan28** [comment]
It seems some ROS packages are missing in your environment. You can try to print out more information to debug.
Here are the lines I added to File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 203, in get_path:

    def get_path(self, name):
        """
        :param name: package name, ``str``
        :returns: filesystem path of package
        :raises: :exc:`ResourceNotFound`
        """
        self._update_location_cache()
        #Debug
        print "+++++resource name: %s" %name
        #Debug
        if name not in self._location_cache:
            raise ResourceNotFound(name, ros_paths=self._ros_paths)
        else:
            #Debug
            print "-----resource location: %s" %self._location_cache[name]
            #Debug
            return self._location_cache[name]

And the correct output should be:
+++++resource name: movidius_ncs_launch
-----resource location: /home/intel/workspace/catkin_ws/install/share/movidius_ncs_launch
+++++resource name: rosgraph
-----resource location: /opt/ros/kinetic/share/rosgraph
... logging to /home/intel/.ros/log/5bf84300-28c4-11e8-9d29-001fc69cba12/roslaunch-intel-desktop-14719.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

+++++resource name: movidius_ncs_launch
-----resource location: /home/intel/workspace/catkin_ws/install/share/movidius_ncs_launch
+++++resource name: realsense_ros_camera
-----resource location: /home/intel/workspace/catkin_ws/install/share/realsense_ros_camera
+++++resource name: movidius_ncs_launch
-----resource location: /home/intel/workspace/catkin_ws/install/share/movidius_ncs_launch
+++++resource name: movidius_ncs_launch
-----resource location: /home/intel/workspace/catkin_ws/install/share/movidius_ncs_launch
started roslaunch server http://intel-desktop:43287/

SUMMARY
========

PARAMETERS
 * /movidius_ncs_nodelet/movidius_ncs_stream/category_file_path: /opt/movidius/nca...
 * /movidius_ncs_nodelet/movidius_ncs_stream/channel1_mean: 104.006987932
 * /movidius_ncs_nodelet/movidius_ncs_stream/channel2_mean: 116.668767617
 * /movidius_ncs_nodelet/movidius_ncs_stream/channel3_mean: 122.678914341
 * /movidius_ncs_nodelet/movidius_ncs_stream/cnn_type: alexnet
 * /movidius_ncs_nodelet/movidius_ncs_stream/device_index: 0
 * /movidius_ncs_nodelet/movidius_ncs_stream/graph_file_path: /opt/movidius/nca...
 * /movidius_ncs_nodelet/movidius_ncs_stream/log_level: 1
 * /movidius_ncs_nodelet/movidius_ncs_stream/network_dimension: 227
 * /movidius_ncs_nodelet/movidius_ncs_stream/scale: 1.0
 * /movidius_ncs_nodelet/movidius_ncs_stream/top_n: 3
 * /realsense_ros_camera/accel_fps: 1000
 * /realsense_ros_camera/accel_optical_frame_id: camera_accel_opti...
 * /realsense_ros_camera/color_fps: 30
 * /realsense_ros_camera/color_height: 480
 * /realsense_ros_camera/color_optical_frame_id: camera_rgb_optica...
 * /realsense_ros_camera/color_width: 640
 * /realsense_ros_camera/depth_fps: 30
 * /realsense_ros_camera/depth_height: 480
 * /realsense_ros_camera/depth_optical_frame_id: camera_depth_opti...
 * /realsense_ros_camera/depth_width: 640
 * /realsense_ros_camera/enable_color: True
 * /realsense_ros_camera/enable_depth: True
 * /realsense_ros_camera/enable_fisheye: True
 * /realsense_ros_camera/enable_imu: True
 * /realsense_ros_camera/enable_infra1: True
 * /realsense_ros_camera/enable_infra2: True
 * /realsense_ros_camera/fisheye_fps: 30
 * /realsense_ros_camera/fisheye_height: 480
 * /realsense_ros_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /realsense_ros_camera/fisheye_width: 640
 * /realsense_ros_camera/gyro_fps: 1000
 * /realsense_ros_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /realsense_ros_camera/infra1_fps: 30
 * /realsense_ros_camera/infra1_height: 480
 * /realsense_ros_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /realsense_ros_camera/infra1_width: 640
 * /realsense_ros_camera/infra2_fps: 30
 * /realsense_ros_camera/infra2_height: 480
 * /realsense_ros_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /realsense_ros_camera/infra2_width: 640
 * /rosdistro: kinetic
 * /rosversion: +++++resource nam...

NODES
  /movidius_ncs_nodelet/
    movidius_manager (nodelet/nodelet)
    movidius_ncs_stream (nodelet/nodelet)
  /
    realsense_ros_camera (nodelet/nodelet)
    realsense_ros_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [14730]
+++++resource name: rosgraph
-----resource location: /opt/ros/kinetic/share/rosgraph
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 5bf84300-28c4-11e8-9d29-001fc69cba12
+++++resource name: rosout
-----resource location: /opt/ros/kinetic/share/rosout
process[rosout-1]: started with pid [14743]
started core service [/rosout]
+++++resource name: nodelet
-----resource location: /opt/ros/kinetic/share/nodelet
process[realsense_ros_camera_manager-2]: started with pid [14760]
+++++resource name: nodelet
-----resource location: /opt/ros/kinetic/share/nodelet
process[realsense_ros_camera-3]: started with pid [14761]
+++++resource name: nodelet
-----resource location: /opt/ros/kinetic/share/nodelet
process[movidius_ncs_nodelet/movidius_manager-4]: started with pid [14762]
+++++resource name: nodelet
-----resource location: /opt/ros/kinetic/share/nodelet
process[movidius_ncs_nodelet/movidius_ncs_stream-5]: started with pid [14769]
[ INFO] [1521168446.116530553]: Loading nodelet /realsense_ros_camera of type realsense_ros_camera/RealSenseCameraNodelet to manager realsense_ros_camera_manager with the following remappings:
[ INFO] [1521168446.118552802]: waitForService: Service [/realsense_ros_camera_manager/load_nodelet] has not been advertised, waiting...
[ INFO] [1521168446.127869524]: Loading nodelet /movidius_ncs_nodelet/movidius_ncs_stream of type movidius_ncs_stream/NCSNodelet to manager movidius_manager with the following remappings:
[ INFO] [1521168446.127951425]: /camera/rgb/image_raw -> /camera/color/image_raw
[ INFO] [1521168446.127971022]: /movidius_ncs_nodelet/classified_object -> /movidius_ncs_nodelet/classified_object
[ INFO] [1521168446.131010926]: Initializing nodelet with 8 worker threads.
[ INFO] [1521168446.132412800]: waitForService: Service [/movidius_ncs_nodelet/movidius_manager/load_nodelet] has not been advertised, waiting...
[ INFO] [1521168446.137407350]: Initializing nodelet with 8 worker threads.
[ INFO] [1521168446.139311751]: waitForService: Service [/realsense_ros_camera_manager/load_nodelet] is now available.
[ INFO] [1521168446.153288749]: waitForService: Service [/movidius_ncs_nodelet/movidius_manager/load_nodelet] is now available.
[ INFO] [1521168446.155790095]: RealSense ROS v2.0.0
[ INFO] [1521168446.155811528]: Running with LibRealSense v2.9.0
[ INFO] [1521168446.156163231]: getParameters...
[ INFO] [1521168446.167291405]: use device_index = 0
[ INFO] [1521168446.167860975]: use log_level = 1
[ INFO] [1521168446.168517903]: use graph_file_path = /opt/movidius/ncappzoo/caffe/AlexNet/graph
[ INFO] [1521168446.169171135]: use category_file_path = /opt/movidius/ncappzoo/data/ilsvrc12/imagenet1000.txt
[ INFO] [1521168446.169788312]: use cnn_type_ = alexnet
[ INFO] [1521168446.170395665]: use network_dimension = 227
[ INFO] [1521168446.171019889]: use channel1_mean = 104.007
[ INFO] [1521168446.171637161]: use channel2_mean = 116.669
[ INFO] [1521168446.172316837]: use channel3_mean = 122.679
[ INFO] [1521168446.173036455]: use top_n = 3
[ INFO] [1521168446.173884630]: use scale = 1
[ INFO] [1521168446.174020395]: open device #0 name=2.5
[ INFO] [1521168446.185153613]: setupDevice...
[ INFO] [1521168446.299520840]: Device Name: Intel RealSense 435
[ INFO] [1521168446.299595754]: Device Serial No: 727212071015
[ INFO] [1521168446.299631001]: Device Product ID: 0B07
[ INFO] [1521168446.300024468]: Device Sensors: 
[ INFO] [1521168446.300356490]: Stereo Module was found.
[ INFO] [1521168446.300421876]: RGB Camera was found.
[ INFO] [1521168446.300721174]: Fisheye sensor isn't supported by current device! -- Skipping...
[ INFO] [1521168446.300765074]: Gyro sensor isn't supported by current device! -- Skipping...
[ INFO] [1521168446.300794856]: Accel sensor isn't supported by current device! -- Skipping...
[ INFO] [1521168446.300879277]: setupPublishers...
[ INFO] [1521168446.485136723]: setupStreams...
[ INFO] [1521168446.487573425]: depth stream is enabled - width: 640, height: 480, fps: 30
[ INFO] [1521168446.487961655]: infra1 stream is enabled - width: 640, height: 480, fps: 30
[ INFO] [1521168446.488256032]: infra2 stream is enabled - width: 640, height: 480, fps: 30
[ INFO] [1521168446.491552604]: color stream is enabled - width: 640, height: 480, fps: 30
[ INFO] [1521168446.508942561]: publishStaticTransforms...
[ INFO] [1521168446.509327956]: RealSense Node Is Up!
Booted 2.5 -> VSC

So please double check the environment on your side and find out which package is missing.

**Comment by manhha1402** [comment]
Here is output of my computer:
+++++resource name: movidius_ncs_launch
-----resource location: /home/jcl-mh/catkin_ws/src/ros_intel_movidius_ncs/movidius_ncs_launch
+++++resource name: rosgraph
-----resource location: /opt/ros/kinetic/share/rosgraph
... logging to /home/jcl-mh/.ros/log/c3c10f5c-2b4f-11e8-b25f-901b0e0c067c/roslaunch-jcl-stud-7478.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

+++++resource name: movidius_ncs_launch
-----resource location: /home/jcl-mh/catkin_ws/src/ros_intel_movidius_ncs/movidius_ncs_launch
+++++resource name: realsense_ros_camera
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/__init__.py", line 306, in main
    p.start()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 268, in start
    self._start_infrastructure()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 217, in _start_infrastructure
    self._load_config()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 132, in _load_config
    roslaunch_strs=self.roslaunch_strs, verbose=self.verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/config.py", line 451, in load_config_default
    loader.load(f, config, verbose=verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 748, in load
    self._load_launch(launch, ros_config, is_core=core, filename=filename, argv=argv, verbose=verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 720, in _load_launch
    self._recurse_load(ros_config, launch.childNodes, self.root_context, None, is_core, verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 654, in _recurse_load
    default_machine, is_core, verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 684, in _recurse_load
    val = self._include_tag(tag, context, ros_config, default_machine, is_core, verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 95, in call
    return f(*args, **kwds)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 588, in _include_tag
    inc_filename = self.resolve_args(tag.attributes['file'].value, context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 183, in resolve_args
    return substitution_args.resolve_args(args, context=context.resolve_dict, resolve_anon=self.resolve_anon)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 370, in resolve_args
    resolved = _resolve_args(resolved, context, resolve_anon, commands)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 383, in _resolve_args
    resolved = commands[command](resolved, a, args, context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 151, in _find
    source_path_to_packages=source_path_to_packages)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 197, in _find_executable
    full_path = _get_executable_path(rp.get_path(args[0]), path)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 204, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
ResourceNotFound: realsense_ros_camera
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/jcl-mh/catkin_ws/src
ROS path [2]=/opt/ros/kinetic/share

I tried to use my own code with realsense + movidius stick, it worked. Here is the result of Alexnet:
![realsense_ncs_ros](https://user-images.githubusercontent.com/20105284/37585173-74890e40-2b58-11e8-9719-c877f55c2cb3.png)
I will check the missing packages.
I just check it out that the realsense node has changed its name to "realsense2_camera", so I think the movidius_ncs_lauch file should be modified as well.
Now I am able to lauch file:
roslaunch movidius_ncs_launch ncs_camera.launch cnn_type:=alexnet camera:=realsense. 
Here is output of rostopic list:
/camera/color/camera_info
/camera/color/image_raw
/camera/color/image_raw/compressed
/camera/color/image_raw/compressed/parameter_descriptions
/camera/color/image_raw/compressed/parameter_updates
/camera/color/image_raw/compressedDepth
/camera/color/image_raw/compressedDepth/parameter_descriptions
/camera/color/image_raw/compressedDepth/parameter_updates
/camera/color/image_raw/theora
/camera/color/image_raw/theora/parameter_descriptions
/camera/color/image_raw/theora/parameter_updates
/camera/depth/camera_info
/camera/depth/image_rect_raw
/camera/depth/image_rect_raw/compressed
/camera/depth/image_rect_raw/compressed/parameter_descriptions
/camera/depth/image_rect_raw/compressed/parameter_updates
/camera/depth/image_rect_raw/compressedDepth
/camera/depth/image_rect_raw/compressedDepth/parameter_descriptions
/camera/depth/image_rect_raw/compressedDepth/parameter_updates
/camera/depth/image_rect_raw/theora
/camera/depth/image_rect_raw/theora/parameter_descriptions
/camera/depth/image_rect_raw/theora/parameter_updates
/camera/extrinsics/depth_to_color
/camera/extrinsics/depth_to_infra1
/camera/extrinsics/depth_to_infra2
/camera/infra1/camera_info
/camera/infra1/image_rect_raw
/camera/infra1/image_rect_raw/compressed
/camera/infra1/image_rect_raw/compressed/parameter_descriptions
/camera/infra1/image_rect_raw/compressed/parameter_updates
/camera/infra1/image_rect_raw/compressedDepth
/camera/infra1/image_rect_raw/compressedDepth/parameter_descriptions
/camera/infra1/image_rect_raw/compressedDepth/parameter_updates
/camera/infra1/image_rect_raw/theora
/camera/infra1/image_rect_raw/theora/parameter_descriptions
/camera/infra1/image_rect_raw/theora/parameter_updates
/camera/infra2/camera_info
/camera/infra2/image_rect_raw
/camera/infra2/image_rect_raw/compressed
/camera/infra2/image_rect_raw/compressed/parameter_descriptions
/camera/infra2/image_rect_raw/compressed/parameter_updates
/camera/infra2/image_rect_raw/compressedDepth
/camera/infra2/image_rect_raw/compressedDepth/parameter_descriptions
/camera/infra2/image_rect_raw/compressedDepth/parameter_updates
/camera/infra2/image_rect_raw/theora
/camera/infra2/image_rect_raw/theora/parameter_descriptions
/camera/infra2/image_rect_raw/theora/parameter_updates
/camera/realsense2_camera_manager/bond
/camera/realsense2_camera_manager/parameter_descriptions
/camera/realsense2_camera_manager/parameter_updates
/movidius_ncs_nodelet/classified_objects
/movidius_ncs_nodelet/movidius_manager/bond
/rosout
/rosout_agg
/tf_static

How can I see the detection on RVIZ ? 
For the image detection. I run:
roslaunch movidius_ncs_launch ncs_image.launch cnn_type:=mobilenetssd
then:
rosrun movidius_ncs_example movidius_ncs_example_image_detection /opt/movidius/ncappzoo/data/images/cat.jpg
output of errror:  [ERROR] [1521451509.349842133]: failed to call service DetectObject

**Comment by xhuan28** [comment]
Thanks for reminding. We don't always follow the latest commit of realsense ros package. We use tag 2.0.2 instead currently and will sync with realsense code accordingly if needed in future.
Currently, we don't implement RVIZ display, but it is in our plan.
Have you fixed the issue that you cannot obtain the image detection result? If yes, please provide more information and we will help you look at this.

**Comment by manhha1402** [comment]
The problem is fixed. Thank you !

**Comment by patrickpoirier51** [comment]
Experienced this problem too with realsense d435 , as @manhha1402  wote ;
_I just check it out that the realsense node has changed its name to "realsense2_camera", so I think the movidius_ncs_lauch file should be modified as well._

I made it -run-with-other-ros-supported-cameras:
roslaunch realsense2_camera rs_camera.launch
roslaunch movidius_ncs_launch ncs_camera.launch cnn_type:=tinyyolo_v1 camera:=others input_topic:=/camera/color/image_raw
