### ISSUE TITLE
No output?

### ISSUE THREAD

**Issue by j5207** [intel/ros_intel_movidius_ncs#65]
![screenshot from 2018-03-16 15-36-40](https://user-images.githubusercontent.com/33009871/37541141-db818ed6-292f-11e8-89e9-3f593328589f.png)

Thanks!

**Comment by xhuan28** [comment]
can you provide more info to locate the issue? It seems an issue of object analytics, suggest you report this issue to object analytics project: https://github.com/intel/ros_object_analytics/issues.

**Comment by j5207** [comment]
Sorry about my previous vague question. The new issue have been posted on another repo. Thanks!
https://github.com/intel/ros_object_analytics/issues/26

**Comment by xhuan28** [comment]
Close it as it is an issue of object analytics.
