### ISSUE TITLE
ROS No output?

### ISSUE THREAD

**Issue by ytgcljj** [intel/ros_intel_movidius_ncs#71]
I want to use ROS to display and detect the image in the ROS and how to modify it

**Comment by ytgcljj** [comment]
![0180326124917](https://user-images.githubusercontent.com/27713475/37887532-d8c41502-30f4-11e8-8d84-7156bcf0bbe7.jpg)

**Comment by xhuan28** [comment]
Did you mean there is no output in Rviz? The feature is in our plan, but not implemented yet. Currently, you can view the result through opencv viewer. If you really need this feature, we can prioritize to enable Rviz display.

**Comment by ytgcljj** [comment]
Yes, I want to do this, thank you.

**Comment by ytgcljj** [comment]
@xhuan28 do it tell me

**Comment by ytgcljj** [comment]
thanks

**Comment by xhuan28** [comment]
We are planning to add this feature in next release. We also welcome contributions from community. So feel free to submit pull request to implement this feature if you like.

**Comment by chaoli2** [comment]
Close this thread since the development plan is changed due to the release of [NCSDK v2](https://github.com/movidius/ncsdk/tree/ncsdk2).
